-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Insert sample colleges into the 'colleges' table
INSERT INTO public.colleges (college_id, name, city, state, university_name, created_at) VALUES
-- Bangalore Colleges
(uuid_generate_v4(), 'Indian Institute of Science', 'Bangalore', 'Karnataka', 'IISc Bangalore', NOW()),
(uuid_generate_v4(), 'R.V. College of Engineering', 'Bangalore', 'Karnataka', 'VTU', NOW()),
(uuid_generate_v4(), 'BMS College of Engineering', 'Bangalore', 'Karnataka', 'VTU', NOW()),
(uuid_generate_v4(), 'PES University', 'Bangalore', 'Karnataka', 'PES University', NOW()),
(uuid_generate_v4(), 'MS Ramaiah Institute of Technology', 'Bangalore', 'Karnataka', 'VTU', NOW()),
(uuid_generate_v4(), 'Christ University', 'Bangalore', 'Karnataka', 'Christ University', NOW()),
(uuid_generate_v4(), 'Dayananda Sagar College of Engineering', 'Bangalore', 'Karnataka', 'VTU', NOW()),
(uuid_generate_v4(), 'Jain University', 'Bangalore', 'Karnataka', 'Jain University', NOW()),
(uuid_generate_v4(), 'Bangalore Institute of Technology', 'Bangalore', 'Karnataka', 'VTU', NOW()),
(uuid_generate_v4(), 'New Horizon College of Engineering', 'Bangalore', 'Karnataka', 'VTU', NOW()),
(uuid_generate_v4(), 'CMR Institute of Technology', 'Bangalore', 'Karnataka', 'VTU', NOW()),
(uuid_generate_v4(), 'Nitte Meenakshi Institute of Technology', 'Bangalore', 'Karnataka', 'VTU', NOW()),
(uuid_generate_v4(), 'Reva University', 'Bangalore', 'Karnataka', 'Reva University', NOW()),
(uuid_generate_v4(), 'Acharya Institute of Technology', 'Bangalore', 'Karnataka', 'VTU', NOW()),
(uuid_generate_v4(), 'East Point College of Engineering and Technology', 'Bangalore', 'Karnataka', 'VTU', NOW()),
(uuid_generate_v4(), 'Global Academy of Technology', 'Bangalore', 'Karnataka', 'VTU', NOW()),
(uuid_generate_v4(), 'Sambhram Institute of Technology', 'Bangalore', 'Karnataka', 'VTU', NOW()),
(uuid_generate_v4(), 'Sir M Visvesvaraya Institute of Technology', 'Bangalore', 'Karnataka', 'VTU', NOW()),
(uuid_generate_v4(), 'T John Institute of Technology', 'Bangalore', 'Karnataka', 'VTU', NOW()),
(uuid_generate_v4(), 'AMC Engineering College', 'Bangalore', 'Karnataka', 'VTU', NOW()),
(uuid_generate_v4(), 'Don Bosco Institute of Technology', 'Bangalore', 'Karnataka', 'VTU', NOW()),
(uuid_generate_v4(), 'Oxford College of Engineering', 'Bangalore', 'Karnataka', 'VTU', NOW()),
(uuid_generate_v4(), 'RajaRajeswari College of Engineering', 'Bangalore', 'Karnataka', 'VTU', NOW()),
(uuid_generate_v4(), 'Sapthagiri College of Engineering', 'Bangalore', 'Karnataka', 'VTU', NOW()),
(uuid_generate_v4(), 'SJB Institute of Technology', 'Bangalore', 'Karnataka', 'VTU', NOW()),
(uuid_generate_v4(), 'Sri Krishna Institute of Technology', 'Bangalore', 'Karnataka', 'VTU', NOW()),
(uuid_generate_v4(), 'Vemana Institute of Technology', 'Bangalore', 'Karnataka', 'VTU', NOW()),
(uuid_generate_v4(), 'Vivekananda Institute of Technology', 'Bangalore', 'Karnataka', 'VTU', NOW()),
(uuid_generate_v4(), 'Bangalore College of Engineering and Technology', 'Bangalore', 'Karnataka', 'VTU', NOW()),
(uuid_generate_v4(), 'Cambridge Institute of Technology', 'Bangalore', 'Karnataka', 'VTU', NOW()),

-- Chennai Colleges
(uuid_generate_v4(), 'Indian Institute of Technology Madras', 'Chennai', 'Tamil Nadu', 'IIT Madras', NOW()),
(uuid_generate_v4(), 'Anna University', 'Chennai', 'Tamil Nadu', 'Anna University', NOW()),
(uuid_generate_v4(), 'SRM Institute of Science and Technology', 'Chennai', 'Tamil Nadu', 'SRM University', NOW()),
(uuid_generate_v4(), 'Sathyabama Institute of Science and Technology', 'Chennai', 'Tamil Nadu', 'Sathyabama University', NOW()),
(uuid_generate_v4(), 'Vellore Institute of Technology Chennai', 'Chennai', 'Tamil Nadu', 'VIT University', NOW()),
(uuid_generate_v4(), 'Loyola College', 'Chennai', 'Tamil Nadu', 'University of Madras', NOW()),
(uuid_generate_v4(), 'Madras Christian College', 'Chennai', 'Tamil Nadu', 'University of Madras', NOW()),
(uuid_generate_v4(), 'Presidency College', 'Chennai', 'Tamil Nadu', 'University of Madras', NOW()),
(uuid_generate_v4(), 'Ethiraj College for Women', 'Chennai', 'Tamil Nadu', 'University of Madras', NOW()),
(uuid_generate_v4(), 'Stella Maris College', 'Chennai', 'Tamil Nadu', 'University of Madras', NOW()),
(uuid_generate_v4(), 'Women''s Christian College', 'Chennai', 'Tamil Nadu', 'University of Madras', NOW()),
(uuid_generate_v4(), 'Meenakshi College for Women', 'Chennai', 'Tamil Nadu', 'University of Madras', NOW()),
(uuid_generate_v4(), 'Queen Mary''s College', 'Chennai', 'Tamil Nadu', 'University of Madras', NOW()),
(uuid_generate_v4(), 'Dr. MGR Educational and Research Institute', 'Chennai', 'Tamil Nadu', 'Dr. MGR University', NOW()),
(uuid_generate_v4(), 'Saveetha Institute of Medical and Technical Sciences', 'Chennai', 'Tamil Nadu', 'Saveetha University', NOW()),
(uuid_generate_v4(), 'Hindustan Institute of Technology and Science', 'Chennai', 'Tamil Nadu', 'Hindustan University', NOW()),
(uuid_generate_v4(), 'Vel Tech Rangarajan Dr. Sagunthala R&D Institute of Science and Technology', 'Chennai', 'Tamil Nadu', 'Vel Tech University', NOW()),
(uuid_generate_v4(), 'Bharath Institute of Higher Education and Research', 'Chennai', 'Tamil Nadu', 'Bharath University', NOW()),
(uuid_generate_v4(), 'Tamil Nadu Dr. M.G.R. Medical University', 'Chennai', 'Tamil Nadu', 'Dr. M.G.R. Medical University', NOW()),
(uuid_generate_v4(), 'Madras Medical College', 'Chennai', 'Tamil Nadu', 'Dr. M.G.R. Medical University', NOW()),
(uuid_generate_v4(), 'Kilpauk Medical College', 'Chennai', 'Tamil Nadu', 'Dr. M.G.R. Medical University', NOW()),
(uuid_generate_v4(), 'Sri Ramachandra Institute of Higher Education and Research', 'Chennai', 'Tamil Nadu', 'Sri Ramachandra University', NOW()),
(uuid_generate_v4(), 'Chettinad Academy of Research and Education', 'Chennai', 'Tamil Nadu', 'Chettinad University', NOW()),
(uuid_generate_v4(), 'Shiv Nadar University Chennai', 'Chennai', 'Tamil Nadu', 'Shiv Nadar University', NOW()),
(uuid_generate_v4(), 'Vels Institute of Science, Technology & Advanced Studies', 'Chennai', 'Tamil Nadu', 'Vels University', NOW()),
(uuid_generate_v4(), 'Dhanalakshmi Srinivasan University', 'Chennai', 'Tamil Nadu', 'Dhanalakshmi Srinivasan University', NOW()),
(uuid_generate_v4(), 'AMET University', 'Chennai', 'Tamil Nadu', 'AMET University', NOW()),
(uuid_generate_v4(), 'B.S. Abdur Rahman Crescent Institute of Science and Technology', 'Chennai', 'Tamil Nadu', 'Crescent University', NOW()),
(uuid_generate_v4(), 'Sree Balaji Medical College and Hospital', 'Chennai', 'Tamil Nadu', 'Bharath University', NOW()),
(uuid_generate_v4(), 'Tagore Medical College and Hospital', 'Chennai', 'Tamil Nadu', 'Dr. M.G.R. Medical University', NOW()),

-- Hyderabad Colleges
(uuid_generate_v4(), 'Indian Institute of Technology Hyderabad', 'Hyderabad', 'Telangana', 'IIT Hyderabad', NOW()),
(uuid_generate_v4(), 'International Institute of Information Technology Hyderabad', 'Hyderabad', 'Telangana', 'IIIT Hyderabad', NOW()),
(uuid_generate_v4(), 'Osmania University', 'Hyderabad', 'Telangana', 'Osmania University', NOW()),
(uuid_generate_v4(), 'Jawaharlal Nehru Technological University Hyderabad', 'Hyderabad', 'Telangana', 'JNTU Hyderabad', NOW()),
(uuid_generate_v4(), 'University of Hyderabad', 'Hyderabad', 'Telangana', 'University of Hyderabad', NOW()),
(uuid_generate_v4(), 'NALSAR University of Law', 'Hyderabad', 'Telangana', 'NALSAR University', NOW()),
(uuid_generate_v4(), 'Chaitanya Bharathi Institute of Technology', 'Hyderabad', 'Telangana', 'Osmania University', NOW()),
(uuid_generate_v4(), 'Vasavi College of Engineering', 'Hyderabad', 'Telangana', 'Osmania University', NOW()),
(uuid_generate_v4(), 'Gokaraju Rangaraju Institute of Engineering and Technology', 'Hyderabad', 'Telangana', 'JNTU Hyderabad', NOW()),
(uuid_generate_v4(), 'Malla Reddy Engineering College', 'Hyderabad', 'Telangana', 'JNTU Hyderabad', NOW()),
(uuid_generate_v4(), 'CVR College of Engineering', 'Hyderabad', 'Telangana', 'JNTU Hyderabad', NOW()),
(uuid_generate_v4(), 'VNR Vignana Jyothi Institute of Engineering and Technology', 'Hyderabad', 'Telangana', 'JNTU Hyderabad', NOW()),
(uuid_generate_v4(), 'Mahindra University', 'Hyderabad', 'Telangana', 'Mahindra University', NOW()),
(uuid_generate_v4(), 'Woxsen University', 'Hyderabad', 'Telangana', 'Woxsen University', NOW());
